name: Built Test Ubuntu

on: [push, pull_request]

jobs:
  build_test_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install libusb
        run: |
          sudo apt install -y libudev-dev

      - name: npm install
        run: |
          npm install

      - name: npm test
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run package
          npm run lint
          npm exec tsc
          npm test

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: installers
          path: |
            release/build/ReplayManagerForSlippi*.AppImage
